name: Backend CI/CD

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: true

      - name: Restore Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-mod-${{ hashFiles('backend todo-app/go.sum') }}
          restore-keys: go-mod-

      - name: Install dependencies
        run: |
          cd backend todo-app  # 🔥 Ensure we're in backend directory
          go mod tidy

      - name: Run tests
        run: |
          cd backend todo-app  # 🔥 Ensure tests run inside backend
          go test ./...

      - name: Build backend
        run: |
          cd backend todo-app  # 🔥 Ensure build runs inside backend
          go build -o backend-app ./main.go  # 🔥 Output binary as backend-app

      - name: Upload backend binary
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: backend todo-app/backend-app
