- name: Set up Go
  uses: actions/setup-go@v4
  with:
    go-version: 1.24 # Adjust based on your Go version
  env:
    GOROOT: /usr/local/go

- name: Change directory to backend
  run: cd backend todo-app  # 🔥 Move into the backend directory

- name: Restore Go cache
  uses: actions/cache@v3
  with:
    path: ~/go/pkg/mod
    key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}  # 🔥 Updated path
    restore-keys: |
      ${{ runner.os }}-go-

- name: Install dependencies
  run: |
    cd backend  # 🔥 Move into backend again
    go mod tidy
    go mod download
